import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ThemeToggleButton from "@/components/ui/light-dark-toggle";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={"h-full"}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-full dark`}
      >
      <ThemeToggleButton className={"fixed top-1/2"}/>
      <div className="layout-wrapper min-h-full flex  flex-col " >
          {/*<Header/>*/}

          <main className={"flex-grow  border-black-100 flex  "}>

              {children}
          </main>
          {/*<Footer/>*/}
      </div>

      </body>
    </html>
  );
}
